### ISSUE TITLE
manpage of k5start does contain invalid examples

### ISSUE THREAD

**Issue by michael-o** [rra/kstart#8]
manpage from https://www.eyrie.org/~eagle/software/kstart/k5start.html says:
```
... -- sh -c 'ls -l $KRB5CCNAME'
```
but it fails with: `ls: cannot access FILE:/tmp/krb5cc_1000_AVrXdq: No such file or directory`
Because the cache name contains the cache type as prefix. One should rather change that `klist`

**Comment by rra** [comment]
`klist` doesn't show the permissions, which was the intent of the example. I've instead changed it to use a more complex shell command that removes the `FILE:` prefix, since that also illustrates how to run a complex shell command under `k5start`. Thanks for the report!
